### ISSUE TITLE
echo-app and plugins are passing builds with errors

### ISSUE THREAD

**Issue by zach-herridge** [PoeStack/poestack-sage#40]
Create a compilation error in a plugin or echo-app
Run `./gradlew npmBuild` at the project root
The build will pass

**Comment by C3ntraX** [comment]
You mean this?

![image](https://github.com/PoeStack/poestack-sage/assets/44802503/542af54f-212d-4a0b-8a5f-d47d3b900007)

**Comment by zach-herridge** [comment]
> You mean this?
> 
> ![image](https://user-images.githubusercontent.com/44802503/284027724-542af54f-212d-4a0b-8a5f-d47d3b900007.png)

<img width="1061" alt="image" src="https://github.com/PoeStack/poestack-sage/assets/6809142/184be5a7-69f3-4ade-88fd-d045bf6b0323">

- Replace something in echo-app with random text to cause error
- `./gradlew npmBuild`
- Build successful

**Comment by C3ntraX** [comment]
- `pluginsMap is decalred but its value is never read` This comes from eslint/typescript and is not an error. Its just an advice you can ignore
- `Cannot fine name 'xxx'` You forgot the quotes. This is not an actual string. You see that typescript cann't interpret this and thinks its of type `any`

I don't see any issues here?

**Comment by C3ntraX** [comment]
https://vitejs.dev/guide/features.html#transpile-only

Vite does only transpile and not type check. 
I'll add typechecking before the build starts. The was also in the electron-vite boilerplate but I thought it was not necessary.

This typechecking does throw errors for type issues.

![image](https://github.com/PoeStack/poestack-sage/assets/44802503/8443362b-9d43-43cd-b277-54824641f6f3)

This too, what I told you.

Even for unused variables which is fine, because vite will ony transpile and include them in the build.

We should add a bot for pull requests, which runs typechecking.
